x-logging: &default-logging
  driver: json-file
  options:
    max-size: "500k"
    max-file: "3"

services:
  postgres:
    image: postgres:18.4-trixie
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data/pgdata
    env_file: .env.postgres
    environment:
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - db_net
    logging: *default-logging

  bot:
    build:
      context: .
      args:
        SERVICE_NAME: bot
    command: python -u -m bot.bot
    volumes:
      - ${DATA_DIR}/telegram-bot-api:/var/lib/telegram-bot-api
      - ${TMP_DIR}:/usr/src/app/${TMP_DIR}
    networks:
      - default
      - db_net
    logging: *default-logging

  clean_orders_queue:
    build:
      context: .
      args:
        SERVICE_NAME: clean_orders_queue
    command: python -u -m tasks.clean_orders_queue
    networks:
      - default
      - db_net
    logging: *default-logging

  build_worker:
    build:
      context: .
      args:
        SERVICE_NAME: build_worker
    runtime: sysbox-runc
    init: true
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}:/usr/src/app/${DATA_DIR}
      - build_worker_docker_data:/var/lib/docker
    command: /bin/sh scripts/start_build_worker.sh
    logging: *default-logging

  workers_controller:
    build:
      context: .
      args:
        SERVICE_NAME: workers_controller
    command: gunicorn -b 0.0.0.0:8000 web.workers_controller:app
    stop_grace_period: 3m
    volumes:
      - ${TMP_DIR}:/usr/src/app/${TMP_DIR}
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - default
      - db_net
    logging: *default-logging

  migrations:
    build:
      context: .
      args:
        SERVICE_NAME: migrations
    command: alembic upgrade head
    networks:
      - default
      - db_net

  tests:
    build:
      context: .
      args:
        SERVICE_NAME: tests
    command: pytest tests/
    networks:
      - default
      - db_net

  tg_bot_api:
    image: aiogram/telegram-bot-api:9.6
    env_file: .env.tg_bot_api
    environment:
      TELEGRAM_LOCAL: 1
    volumes:
      - ${DATA_DIR}/telegram-bot-api:/var/lib/telegram-bot-api
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8082:8082"
    logging: *default-logging

volumes:
  build_worker_docker_data:

networks:
  db_net:
    internal: true
