"""add keystore to order

Revision ID: a1b81ff163a8
Revises: 898b8f6137b0
Create Date: 2024-09-17 11:37:39.342777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b81ff163a8'
down_revision = '898b8f6137b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keystore', postgresql.BYTEA(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('keystore')

    # ### end Alembic commands ###
