"""add customization options

Revision ID: 898b8f6137b0
Revises: 2699b2a4016b
Create Date: 2024-09-07 19:28:55.281731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '898b8f6137b0'
down_revision = '2699b2a4016b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_version_code', sa.INTEGER(), server_default='100', nullable=True))
        batch_op.add_column(sa.Column('app_version_name', sa.String(), server_default='1.0.0', nullable=True))
        batch_op.add_column(sa.Column('app_notification_icon', postgresql.BYTEA(), nullable=True))
        batch_op.add_column(sa.Column('app_notification_color', sa.INTEGER(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('app_masked_passcode_screen', sa.String(), server_default='calculator', nullable=True))
        batch_op.add_column(sa.Column('app_notification_text', sa.String(), server_default='Update Available!', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('app_notification_text')
        batch_op.drop_column('app_masked_passcode_screen')
        batch_op.drop_column('app_notification_color')
        batch_op.drop_column('app_notification_icon')
        batch_op.drop_column('app_version_name')
        batch_op.drop_column('app_version_code')

    # ### end Alembic commands ###
