"""add permissions to order

Revision ID: f19388c14888
Revises: 17c183fddb02
Create Date: 2024-10-20 04:44:00.534344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19388c14888'
down_revision = '17c183fddb02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.String(), server_default='Update Available!', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
