"""add keystore password salt

Revision ID: be411473d47e
Revises: c29b740f4c61
Create Date: 2024-12-22 23:09:07.768717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be411473d47e'
down_revision = 'c29b740f4c61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keystore_password_salt', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('keystore_password_salt')

    # ### end Alembic commands ###
