"""add user build stats

Revision ID: f120292fa0f5
Revises: eda6b02df972
Create Date: 2024-11-01 14:21:29.519438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f120292fa0f5'
down_revision = 'eda6b02df972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_build_stats',
    sa.Column('user_id_hash', sa.String(), nullable=False),
    sa.Column('last_build_date', sa.DateTime(), nullable=False),
    sa.Column('successful_build_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_build_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('user_id_hash', name=op.f('pk_user_build_stats'))
    )
    with op.batch_alter_table('user_build_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_build_stats_last_build_date'), ['last_build_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_build_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_build_stats_last_build_date'))

    op.drop_table('user_build_stats')
    # ### end Alembic commands ###
