"""add messages_to_delete

Revision ID: 7bdb31a2e08c
Revises: beadd5b6258d
Create Date: 2025-01-09 14:37:37.757533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdb31a2e08c'
down_revision = 'beadd5b6258d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_to_delete',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'message_id', name=op.f('pk_messages_to_delete'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_to_delete')
    # ### end Alembic commands ###
